from enum import Enum


class MessageType(Enum):
    BOOLEAN = "BOOLEAN"
    INT = "INT"
    FIXED_LENGTH_STRING = "FIXED_LENGTH_STRING"
    VARIABLE_LENGTH_STRING = "FIXED_LENGTH_STRING"
    FLOAT = "FLOAT"
    HEADER = "HEADER"
    BODY = "BODY"
